### PR TITLE
Node hierarchy codegen

### PR DESCRIPTION
**Pull request by kazimuth**
Starting to implement codegen for the node hierarchy discussed in https://github.com/dmlc/tvm/issues/2983.

My current test script:
```python
from codegen.dsl import *
from codegen.generators import cpp

with API('Test API.') as api:
    Color = node('Color', '_color', 'A color.') \
        .attr('r', int64) \
        .attr('g', int64) \
        .attr('b', int64)

    Apple = node('Apple', '_apple', 'A scrumptious apple.') \
        .attr('color', Color)

print(str(cpp.generate(api)))
```

Output from the test script (incorrect, but illustrative):
```cpp
/// Test API.

/// A color.
class ColorNode {
public:
  int64_t r;
  int64_t g;
  int64_t b;
}
class Color: NodeRef<ColorNode> {}

/// A scrumptious apple.
class AppleNode {
public:
  Color color;
}
class Apple: NodeRef<AppleNode> {}
```

TODO:

- [ ] decide on any updates to the Node API / other semantics we want to change
- [ ] create generators for each of the languages we want to auto-generate nodes for
- [ ] create hierarchy definitions for each Node hierarchy (Halide, Relay, ?)
- [ ] run generation scripts during build
- [ ] set up CI to mypy+lint generation scripts
- [ ] set up CI to make sure generated code is checked in (if we want to check it in)
- [ ] pass existing python tests without any code changes

cc @tqchen @jroesch @junrushao1994

### CODE REVIEW

**Comment by jroesch** [comment]
@tqchen and I have been talking about this for a while. This is a good start, we are happy to let you take over the work but a few design constraints are probably worth elaborating on.

One idea we had was reusing the Python syntax to declare the `Node`s directly.

```
@tvm_node
class A:
    attr1: AttrType
    ...
```

It is important that we build an AST representing the node structure, so we can generate bindings in many languages.

We would like to also move away from using C++ native types in the code generation, and use TVM alternatives that we control.

For example, passing std::string between languages is problematic due the fact that we can't control layout/ownership of the data. There are a few other examples of data structures that are only availble in C++.

A challenge is the current Node system makes heavy use of virtual methods which makes it hard to expose in other languages due the lack of introspection into the VTable. 

Finally I think we should potentially do this generation inside of TVM to start. @tqchen and I have been talking about unifying the ASTs into a single AST and removing the distinction between HalideIR and Relay. 

Maybe Tianqi can weigh in on what he thinks we should do.

**Comment by tqchen** [comment]
I think as a starting point, we could do some quick proptotyping to get ast system that is relatively independent, then we do a global replacement of the node

**Comment by kazimuth** [comment]
i was just throwing code around, if this is high-priority i don't want to block things. But yeah, this makes sense.

**Comment by jroesch** [comment]
@kazimuth if you have some cycles it would be great to get you more involved, Tianqi and I are both super busy and would be happy to have help from the community.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/issues/3501

**Pull request closed without merging**
