### PR TITLE
Simplify to const value variables that are single point

### LINKED ISSUE #51: Simplify single point variables
Currently, if we have a variable that can only assume a single const value (e.g., iteration variable of a loop that has a count of 1), `Simplify` doesn't simplify it to that const value.

### PR DESCRIPTION
**Pull request by derisavi**
This is a simple fix. @tqchen can you please review? This fixes #51.

### CODE REVIEW

**Comment by tqchen** [comment]
Given https://github.com/dmlc/tvm/issues/2588, let us try to solve this problem in the context of the new unified analyzer

**Comment by derisavi** [comment]
I haven't followed the new analayzer very closely. Is it enabled now? If not, do you have an idea when you will enable it?

**Comment by tqchen** [comment]
It is not enabled by default, but I hope we can do soon(in a few weeks)

**Comment by tqchen** [comment]
Given dmlc/tvm#2588 is now migrated

**Pull request closed without merging**
